org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=zombieimprovements
mod.name=Zombie Improvements
mod.group=me.pajic
mod.version=1.2.2
mod.channel_tag=
mod.authors=pajic
mod.contributors=ThePotatoArchivist
mod.license=MIT
mod.description=Improves zombie leader and reinforcement mechanics and fixes a few bugs
mod.sources_url=https://github.com/pajicadvance/zombie-improvements
mod.homepage_url=https://modrinth.com/mod/zombieimprovements
mod.issues_url=https://github.com/pajicadvance/zombie-improvements/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]

publish.modrinth=1NeE16sL
publish.curseforge=1337487
publish.github=false
